/**
  ******************************************************************************
  * @file    Project/STM32L1xx_StdPeriph_Template/stm32l1xx_it.c 
  * @author  MCD Application Team
  * @version V1.0.3
  * @date    May-2013
  * @brief   Main Interrupt Service Routines.
  *          This file provides template for all exceptions handler and 
  *          peripherals interrupt service routine.
  ******************************************************************************
  * @attention
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * <h2><center>&copy; COPYRIGHT 2010 STMicroelectronics</center></h2>
  ******************************************************************************
  */ 

/* Includes ------------------------------------------------------------------*/
#include "board.h"
#include "sensor_init.h"

/** @addtogroup Template_Project
  * @{
  */
	uint8_t timecount ;
  
/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/

/******************************************************************************/
/*            Cortex-M3 Processor Exceptions Handlers                         */
/******************************************************************************/

/**
  * @brief  This function handles NMI exception.
  * @param  None
  * @retval None
  */
void NMI_Handler(void)
{
}

/**
  * @brief  This function handles Hard Fault exception.
  * @param  None
  * @retval None
  */
void HardFault_Handler(void)
{
  /* Go to infinite loop when Hard Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Memory Manage exception.
  * @param  None
  * @retval None
  */
void MemManage_Handler(void)
{
  /* Go to infinite loop when Memory Manage exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Bus Fault exception.
  * @param  None
  * @retval None
  */
void BusFault_Handler(void)
{
  /* Go to infinite loop when Bus Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Usage Fault exception.
  * @param  None
  * @retval None
  */
void UsageFault_Handler(void)
{
  /* Go to infinite loop when Usage Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles SVCall exception.
  * @param  None
  * @retval None
  */
void SVC_Handler(void)
{
}

/**
  * @brief  This function handles Debug Monitor exception.
  * @param  None
  * @retval None
  */
void DebugMon_Handler(void)
{
}

/**
  * @brief  This function handles PendSVC exception.
  * @param  None
  * @retval None
  */
void PendSV_Handler(void)
{
}

/**
  * @brief  This function handles SysTick Handler.
  * @param  None
  * @retval None
  */
void SysTick_Handler(void)
{
    //TimingDelay_Decrement();
}
/******************************************************************************/
/*                 STM32L1xx Peripherals Interrupt Handlers                   */
/*  Add here the Interrupt Handler for the used peripheral(s) (PPP), for the  */
/*  available peripheral interrupt handler's name please refer to the startup */
/*  file (startup_stm32l1xx_md.s).                                            */
/******************************************************************************/

/**
  * @brief  This function handles DMA Transfer Complete interrupt request.
  * @param  None
  * @retval None
  */
//void DMA1_Channel1_IRQHandler    (void)
//{
  //DMA_ClearFlag(DMA1_IT_TC1);
  //setADCDMA_TransferComplete();  /* set flag_ADCDMA_TransferComplete global flag */
//}


/**
  * @brief  This function handles RTC Auto wake-up interrupt request.
  * @param  None
  * @retval None
  */
void RTC_WKUP_IRQHandler(void)
{
}

/**
  * @brief  This function handles external interrupts generated by Ultrasonic ECHO.
  * @param  None
  * @retval None
  */

void EXTI0_IRQHandler(void)
{

	if(EXTI_GetITStatus(EXTI_Line0) != RESET)  
	{				                    
		 UWave_Distance = Ultrasonic_GetData();
		 EXTI_ClearITPendingBit(EXTI_Line0);
	}

}
void EXTI2_IRQHandler(void)
{
	SX1278_Interupt();
	EXTI_ClearITPendingBit(EXTI_Line2);    // Clear the EXTI line 5 pending bit  
}

void EXTI3_IRQHandler(void)
{
	SX1278_Interupt();
	EXTI_ClearITPendingBit(EXTI_Line3);    // Clear the EXTI line 5 pending bit  
}
void EXTI4_IRQHandler(void)
{
	SX1278_Interupt();
	EXTI_ClearITPendingBit(EXTI_Line4);    // Clear the EXTI line 5 pending bit  
}
void EXTI9_5_IRQHandler(void)
{
	#ifdef KEY_INTERRUPT
		
	if(EXTI_GetITStatus(EXTI_Line5) != RESET)      // key2
  {   

		EXTI_ClearITPendingBit(EXTI_Line5);          // Clear the EXTI line 5 pending bit   
  }
 	if(EXTI_GetITStatus(EXTI_Line6) != RESET)      // key3
  {          
		EXTI_ClearITPendingBit(EXTI_Line6);         // Clear the EXTI line 6 pending bit   
  } 
	if(EXTI_GetITStatus(EXTI_Line7) != RESET)     // key4
  {          
		EXTI_ClearITPendingBit(EXTI_Line7);         // Clear the EXTI line 7 pending bit   
  }
		if(EXTI_GetITStatus(EXTI_Line8) != RESET)  // key1
  {          
		EXTI_ClearITPendingBit(EXTI_Line8);        // Clear the EXTI line 8 pending bit   
  }
 #endif	
}
/**
  * @brief  This function handles EXTI15_10_IRQHandler interrupt request.
  * @param  None
  * @retval None
  */
void EXTI15_10_IRQHandler(void)
{
	
	if(EXTI_GetITStatus(EXTI_Line13) != RESET)  
  {          
		Sensor_Module_Address = Sensor_Address_Read();
		//printf("Address is %x \r\n",Sensor_Module_Address);
		//OLED_ShowNum(90,2,Sensor_Module_Address,3,16);
		EXTI_ClearITPendingBit(EXTI_Line13);    // Clear the EXTI line 13 pending bit   
  } 
	if(EXTI_GetITStatus(EXTI_Line15) != RESET)  
  {          
		EXTI_ClearITPendingBit(EXTI_Line15);    // Clear the EXTI line 5 pending bit   
  } 
}
/*************************************************************
  Function   ：TIM2_IRQHandler  
  Description：中断服务函数
  Input      : none        
  return     : none    
*************************************************************/
void TIM3_IRQHandler(void)   //TIM3中断
{
	static uint8_t heart_led_count;
	if (TIM_GetITStatus(TIM3, TIM_IT_Update) != RESET) //检查指定的TIM中断发生与否:TIM 中断源 
	{
			heart_led_count++;
			timecount++;
			if(heart_led_count==25)
			{
				heart_led_count=0;
				LED_Write(RUN_LED,TOGGLE);
			}
			TIM_ClearITPendingBit(TIM3, TIM_IT_Update  );  //清除TIMx的中断待处理位:TIM 中断源 
	}
}


/*************************************************************
  Function   ：TIM2_IRQHandler  
  Description：中断服务函数
  Input      : none        
  return     : none    
*************************************************************/
void TIM2_IRQHandler(void)   
{
	if (TIM_GetITStatus(TIM2, TIM_IT_Update) != RESET) //检查指定的TIM中断发生与否:TIM 中断源 
	{
		TIM_ClearITPendingBit(TIM2, TIM_IT_Update  );  //清除TIMx的中断待处理位:TIM 中断源 
	}
}
/**
  * @}
  */ 


/******************* (C) COPYRIGHT 2010 STMicroelectronics *****END OF FILE****/
